### ISSUE TITLE
wanna run the program

### ISSUE THREAD

**Issue by Bownnw** [pengmun/DESTOPy#1]
Dear sir/madam,
I am an engineering student and now calculated the TLE in many aspects. That I have downloaded all the needed Dependencies and files and put them into the Data file.
When I start the program everything is fine, but when running the cell of 'Run unscented Kalman filter', it prompts an error!

0 24
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\WNT\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\WNT\anaconda3\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\WNT\DESTOPy-ae771d5140d20cb35dd9ef156055ff8bf49e3091\python_utils\astro_function_jit.py", line 2001, in propagateState_MeeBcRom
    xf_out = ode_ope.integrate(tf)
  File "C:\Users\WNT\anaconda3\lib\site-packages\scipy\integrate\_ode.py", line 433, in integrate
    self._y, self.t = mth(self.f, self.jac or (lambda: None),
  File "C:\Users\WNT\anaconda3\lib\site-packages\scipy\integrate\_ode.py", line 1009, in run
    y1, t, istate = self.runner(*args)
  File "C:\Users\WNT\DESTOPy-ae771d5140d20cb35dd9ef156055ff8bf49e3091\python_utils\astro_function_jit.py", line 1756, in computeDerivative_PosVelBcRom
    x2 = x[b].transpose(1, 0, 2).reshape(3,-1)
IndexError: index 1146574368 is out of bounds for axis 0 with size 150
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_29436\3028581531.py in <module>
      1 # Run Unscented Kalman filter estimation
----> 2 X_est,Pv = UKF(X_est,Meas,time,P,RM,Q,nop,svs,r, AC, BC, SWinputs, F_U, M_U, maxAtmAlt, et0, jd0, highFidelity, GM, Re, C_gravmodel,S_gravmodel, gravdegree, sF_gravmod)
      3 Pv[:,0] = np.diag(P); # Add initial state variance to state variance history

~\DESTOPy-ae771d5140d20cb35dd9ef156055ff8bf49e3091\python_utils\astro_function_jit.py in UKF(X_est, Meas, time, P, RM, Q, nop, svs, r, AC, BC, SWinputs, F_U, M_U, maxAtmAlt, et0, jd0, highFidelity, GM, Re, C_gravmodel, S_gravmodel, gravdegree, sF_gravmod)
   2110         # Time Update
   2111         with poolcontext(processes=multiprocessing.cpu_count()-1 or 1) as pool:
-> 2112             Xp = pool.map(partial(propagateState_MeeBcRom, t0=time[i], tf=time[i+1], AC=AC, BC=BC, SWinputs=SWinputs, r=r, nop=nop, svs=svs, F_U=F_U, M_U=M_U,maxAtmAlt=maxAtmAlt,et0=et0,jdate0=jd0,highFidelity=highFidelity,GM=GM, Re=Re, C_gravmodel=C_gravmodel, S_gravmodel=S_gravmodel, gravdegree=gravdegree, sF_gravmod=sF_gravmod), xx.T)
   2113 
   2114         Xp = np.squeeze(np.asarray(Xp).T)

~\anaconda3\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

~\anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

IndexError: index 1146574368 is out of bounds for axis 0 with size 150

I have checked all of the parameters, and could not find the reason. I am wondering you could help me to solve the problem!
Thank you a lot!!!

**Comment by pengmun** [comment]
Hi ROINT,

I was not able to reproduce your error on my machine. Did you change any of the parameters in the Jupyter notebook file? 

It could also be caused by a dependencies error. The code was tested on a linux system with Python 3.7 and the following package version:
- numpy: 1.18.5
- scipy: 1.4.1

Can you run the following codes right before the cell for 'Run unscented Kalman filter' and share the printout here?
`a = np.arange(X_est.shape[0])`
`b = np.lib.stride_tricks.as_strided(a, (nop,3), (8*7,8))`
`print(b)`

b should be a 20 by 3 array with a maximum value of 135. Based on the error, it seems that the value b calculated at line 1755 of astro_function_jit.py is 1146574368 (which is invalid).

**Comment by Bownnw** [comment]
Hi Pengmun,

Thank you for your response!! 
My PC runs on Windows10, and python 3.8. The package version is numpy 1.21.5 and scipy 1.8.0

I have changed some code as follows:
1. The space weather data download from CelesTrak, the first error began in the read file function, I found the `n_daily_obs` is begin from the line 15. And I checked other read file functions and changed them, after that the error is dealt with.

2. I found that the `nut80.dat, ROMDensityModels` is missing in your program, so I find the origin of David Gondelach's Matlab file and put it in.

3. I RUN your instruction lines. Found that **b** shape is (20, 3), but the maximum value is very large
[[         0          2          4]
 [        14         16         18]
 [        28         30         32]
 [        42         44         46]
 [        56         58         60]
 [        70         72         74]
 [        84         86         88]
 [        98        100        102]
 [       112        114        116]
 [       126        128        130]
 [       140        142        144]
 [1212798752        538         -1]
 [ 808335670  540488503  959985456]
 [ 908075040  926169400  542842912]
 [ 774774839  925904441  538982195]
 [ 959985456  959848480  859255865]
 [ 959985456  538976266  959985456]
 [ 926103348  943140910  774774839]
 [ 876165175 1528832010  959985456]
 [ 808335670  540488503  959985456]]

I'm still working on it!

**Comment by pengmun** [comment]
Hi ROINT,

Your code should work once you replace line 1754 and 1755 in the astro_function_jit.py with the following:
`a = np.reshape(np.arange(noo*7),(noo,-1))`
`b = a[:,:3]`

**Comment by Bownnw** [comment]
Hi Pengmun，

Sorry, I have been prepared for a class last week.
Since the last time you feedback, I have checked the code and found a Runtime error about 

```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Then I searched in Stackoverflow, which said was about multiprocessing in Windows system. 
So I installed Linux and configuration needed files.

**But** the program still can't run through the UKF "Run unscented Kalman filter".
The line 2112 in astro_function_jit.py  `Xp = pool.map()` rasised a **TimeoutError**.

I try to set the multiprocessing pool in 1 CPU, still could not work.

**Comment by pengmun** [comment]
Can you replace the following lines in astro_function_jit.py

```
with poolcontext(processes=multiprocessing.cpu_count()-1 or 1) as pool:
   Xp = pool.map(partial(propagateState_MeeBcRom, t0=time[i], tf=time[i+1], AC=AC, BC=BC, SWinputs=SWinputs, r=r, nop=nop, svs=svs, F_U=F_U, M_U=M_U,maxAtmAlt=maxAtmAlt,et0=et0,jdate0=jd0,highFidelity=highFidelity,GM=GM, Re=Re, C_gravmodel=C_gravmodel, S_gravmodel=S_gravmodel, gravdegree=gravdegree, sF_gravmod=sF_gravmod), xx.T)
   Xp = np.squeeze(np.asarray(Xp).T)
```
with

```
Xp= np.zeros_like(xx)
for ik_xp in range(xx.shape[1]):
   print(ik_xp)
   Xp[:,ik_xp] = propagateState_MeeBcRom(xx[:,ik_xp],t0=time[i], tf=time[i+1], AC=AC, BC=BC, SWinputs=SWinputs, r=r, nop=nop, svs=svs, F_U=F_U, M_U=M_U,maxAtmAlt=maxAtmAlt,et0=et0,jdate0=jd0,highFidelity=highFidelity,GM=GM, Re=Re, C_gravmodel=C_gravmodel, S_gravmodel=S_gravmodel, gravdegree=gravdegree, sF_gravmod=sF_gravmod).flatten()
```

It will output an increasing integer to show that the propagateState_MeeBcRom function is running and which sigma point it is currently evaluating. 

**Note**: the for loop will be very slow compared to the multiprocessing code that was replaced.

**Comment by Bownnw** [comment]
Thank you very much, pengmun!!
The program could work, after nearly 24-hour calculation :)
I will learn from it and may change it to the original version (using the multiprocessing) later.
thank you again!
