### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by NIWNIW111** [pengmun/DESTOPy#2]
Dear sir/madam,
I am an engineering student and I'm doing some work on the atmosphere. That I have downloaded all the needed Dependencies and files and put them into the Data file. However, there was an error in “Generate reduced-order density model ”section.

display IndexError: index 0 is out of bounds for axis 0 with size 0

I checked all the parameters, but I haven't found the problem yet，I'd like some guidance. I'd appreciate it。

error：
IndexError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_5920\3705748063.py in <module>
      1 ## Load reduced-order density models
----> 2 AC,BC,Uh,F_U,Dens_Mean,M_U,SLTm,LATm,ALTm,maxAtmAlt,SWinputs,Qrom = generateROMdensityModel(ROMmodel,r,jd0,jdf,spice)

D:\Code2024\py1\DESTOPy-main\DESTOPy-main\python_utils\astro_function_jit.py in generateROMdensityModel(ROMmodel, r, jd0, jdf, spice)
   1271     # Read geomagnetic storm DTC values
   1272     DTCdata = readDTCFILE('Data/DTCFILE.txt');
-> 1273     SWinputs = computeSWinputs_JB2008(jd0,jdf+1,eopdata,SOLdata,DTCdata,spice);
   1274 
   1275     # Maximum altitude of ROM-JB2008 density model (for higher altitudes

D:\Code2024\py1\DESTOPy-main\DESTOPy-main\python_utils\astro_function_jit.py in computeSWinputs_JB2008(jd0, jdf, eopdata, SOLdata, DTCdata, spice)
   1169         UThrs = hhUTC + mnmnUTC/60 + ssUTC/3600;
   1170         # Get JB2008 space weather data
-> 1171         _,GWRAS,SUN,F10,F10B,S10,S10B,XM10,XM10B,Y10,Y10B,DSTDTC = computeJB2000SWinputs(yyUTC,doyUTC,hhUTC,mnmnUTC,ssUTC,SOLdata,DTCdata,eopdata,spice);
   1172 
   1173         # [jdate; doy; UThrs; F10; F10B; S10; S10B; XM10; XM10B; Y10; Y10B; DSTDTC; GWRAS; SUN(1); SUN(2)]

D:\Code2024\py1\DESTOPy-main\DESTOPy-main\python_utils\astro_function_jit.py in computeJB2000SWinputs(year, doy, hour, minute, sec, SOLdata, DTCdata, eopdata, spice)
   1087     # USE 1 DAY LAG FOR F10 AND S10 FOR JB2008
   1088     JD = np.rint(JD_0)-1; # 1 day lag (JD=MJD+2400000.5)
-> 1089     i = np.where(JD==SOLdata[2,:])[0][0];
   1090     SOL = SOLdata[:,i];
   1091     F10 = SOL[3];

IndexError: index 0 is out of bounds for axis 0 with size 0

![NMWI61BV1M KI5%VPCG~YU8](https://github.com/pengmun/DESTOPy/assets/156312073/3962cf80-5d3b-499b-897c-78c0e1a45651)

**Comment by NIWNIW111** [comment]
Is it because of the update of this file that the format reading problem occurred, because the SOL file was updated a few days ago

**Comment by pengmun** [comment]
Yes, the format reading error was caused by a change in the space weather data format. I have patched the space weather function and the code should work now.
